SET SERVEROUTPUT ON;
SHOW ERRORS;
/
CREATE SEQUENCE address_seq START WITH 1;
CREATE SEQUENCE payment_seq START WITH 1;
CREATE SEQUENCE payment_form_seq START WITH 1;
CREATE SEQUENCE country_seq START WITH 10;
CREATE SEQUENCE guest_seq START WITH 1;
CREATE SEQUENCE location_seq START WITH 10;
CREATE SEQUENCE order_seq START WITH 1;
CREATE SEQUENCE sessions_seq START WITH 1;
CREATE SEQUENCE trip_seq START WITH 1;
CREATE SEQUENCE user_seq START WITH 1;
/
CREATE OR REPLACE TRIGGER address_bir
BEFORE
INSERT ON address
FOR EACH ROW BEGIN
SELECT address_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER country_bir
BEFORE
INSERT ON country
FOR EACH ROW BEGIN
SELECT country_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER guest_bir
BEFORE
INSERT ON guest
FOR EACH ROW BEGIN
SELECT guest_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER location_bir
BEFORE
INSERT ON location
FOR EACH ROW BEGIN
SELECT location_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER order_bir
BEFORE
INSERT ON "order"
FOR EACH ROW BEGIN
SELECT order_seq.NEXTVAL INTO :new.id
FROM dual; END;

/
CREATE OR REPLACE TRIGGER payment_bir
BEFORE
INSERT ON payment
FOR EACH ROW BEGIN
SELECT payment_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER payment_form_bir
BEFORE
INSERT ON payment_form
FOR EACH ROW BEGIN
SELECT payment_form_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER sessions_bir
BEFORE
INSERT ON sessions
FOR EACH ROW BEGIN
SELECT sessions_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER trip_bir
BEFORE
INSERT ON trip
FOR EACH ROW BEGIN
SELECT trip_seq.NEXTVAL INTO :new.id
FROM dual; END;
/
CREATE OR REPLACE TRIGGER user_bir
BEFORE
INSERT ON "user"
FOR EACH ROW BEGIN
SELECT user_seq.NEXTVAL INTO :new.id
FROM dual; END;
